credentials:
  usernames:
    user1:
      email: user1@example.com
      name: User One
      password: hashed_password1
    user2:
      email: user2@example.com
      name: User Two
      password: hashed_password2

cookie:
  name: nome_do_cookie
  key: chave_secreta
  expiry_days: 30
